# Generated by Django 5.1.5 on 2025-02-04 11:20

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0004_alter_transaction_options_dailyprofit_total_profit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'verbose_name_plural': 'Transactions'},
        ),
        migrations.RemoveConstraint(
            model_name='dailyprofit',
            name='unique_daily_profit_per_user',
        ),
        migrations.AlterUniqueTogether(
            name='dailyprofit',
            unique_together={('date', 'user')},
        ),
        migrations.RemoveField(
            model_name='dailyprofit',
            name='total_profit',
        ),
    ]
