# Generated by Django 5.1.6 on 2025-02-12 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0006_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='user',
        ),
    ]
